//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class RefCountProxy : IRefCount, global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal RefCountProxy(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(RefCountProxy obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(RefCountProxy obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~RefCountProxy() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new global::System.MethodAccessException("C++ destructor does not have public access");
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
  global::System.Runtime.InteropServices.HandleRef IRefCount.GetInterfaceCPtr() {
    return new global::System.Runtime.InteropServices.HandleRef(this, MediasoupClientPINVOKE.RefCountProxy_IRefCount_GetInterfaceCPtr(swigCPtr.Handle));
  }

  public RefCountProxy(IRefCount instance) : this(MediasoupClientPINVOKE.new_RefCountProxy(), true) {
    swigDelegate0 = new SwigDelegateRefCountProxy_0(() => instance.AddRef());
    swigDelegate1 = new SwigDelegateRefCountProxy_1(() => (int)instance.Release());
    MediasoupClientPINVOKE.RefCountProxy_director_connect(swigCPtr, swigDelegate0, swigDelegate1);
  }

  public virtual void AddRef() {
    MediasoupClientPINVOKE.RefCountProxy_AddRef(swigCPtr);
  }

  public virtual RefCountReleaseStatus Release() {
    RefCountReleaseStatus ret = (RefCountReleaseStatus)MediasoupClientPINVOKE.RefCountProxy_Release(swigCPtr);
    return ret;
  }

  public RefCountProxy() : this(MediasoupClientPINVOKE.new_RefCountProxy(), true) {
    SwigDirectorConnect();
  }

  private void SwigDirectorConnect() {
    if (SwigDerivedClassHasMethod("AddRef", swigMethodTypes0))
      swigDelegate0 = new SwigDelegateRefCountProxy_0(SwigDirectorMethodAddRef);
    if (SwigDerivedClassHasMethod("Release", swigMethodTypes1))
      swigDelegate1 = new SwigDelegateRefCountProxy_1(SwigDirectorMethodRelease);
    MediasoupClientPINVOKE.RefCountProxy_director_connect(swigCPtr, swigDelegate0, swigDelegate1);
  }

  private bool SwigDerivedClassHasMethod(string methodName, global::System.Type[] methodTypes) {
    global::System.Reflection.MethodInfo[] methodInfos = this.GetType().GetMethods(
        global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance);
    foreach (global::System.Reflection.MethodInfo methodInfo in methodInfos) {
      if (methodInfo.DeclaringType == null)
        continue;

      if (methodInfo.Name != methodName)
        continue;

      var parameters = methodInfo.GetParameters();
      if (parameters.Length != methodTypes.Length)
        continue;

      bool parametersMatch = true;
      for (var i = 0; i < parameters.Length; i++) {
        if (parameters[i].ParameterType != methodTypes[i]) {
          parametersMatch = false;
          break;
        }
      }

      if (!parametersMatch)
        continue;

      if (methodInfo.IsVirtual && (methodInfo.DeclaringType.IsSubclassOf(typeof(RefCountProxy))) &&
        methodInfo.DeclaringType != methodInfo.GetBaseDefinition().DeclaringType) {
        return true;
      }
    }

    return false;
  }

  private void SwigDirectorMethodAddRef() {
    AddRef();
  }

  private int SwigDirectorMethodRelease() {
    return (int)Release();
  }

  internal delegate void SwigDelegateRefCountProxy_0();
  internal delegate int SwigDelegateRefCountProxy_1();

  private SwigDelegateRefCountProxy_0 swigDelegate0;
  private SwigDelegateRefCountProxy_1 swigDelegate1;

  private static global::System.Type[] swigMethodTypes0 = new global::System.Type[] {  };
  private static global::System.Type[] swigMethodTypes1 = new global::System.Type[] {  };
}
