//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum RTCErrorType {
  NONE,
  UNSUPPORTED_OPERATION,
  UNSUPPORTED_PARAMETER,
  INVALID_PARAMETER,
  INVALID_RANGE,
  SYNTAX_ERROR,
  INVALID_STATE,
  INVALID_MODIFICATION,
  NETWORK_ERROR,
  RESOURCE_EXHAUSTED,
  INTERNAL_ERROR,
  OPERATION_ERROR_WITH_DATA
}
