/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_MediasoupClient_WRAP_H_
#define SWIG_MediasoupClient_WRAP_H_

class SwigDirector_RefCountProxy : public rtc::RefCountInterface, public Swig::Director {

public:
    SwigDirector_RefCountProxy();
    virtual void AddRef() const;
    virtual rtc::RefCountReleaseStatus Release() const;
    virtual ~SwigDirector_RefCountProxy();

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)();
    typedef int (SWIGSTDCALL* SWIG_Callback1_t)();
    void swig_connect_director(SWIG_Callback0_t callbackAddRef, SWIG_Callback1_t callbackRelease);

private:
    SWIG_Callback0_t swig_callbackAddRef;
    SWIG_Callback1_t swig_callbackRelease;
    void swig_init_callbacks();
};


#endif
