/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


#define SWIG_VERSION 0x040101
#define SWIGCSHARP
#define SWIG_DIRECTORS

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


#include <stdlib.h>
#include <string.h>
#include <stdio.h>


/* Support for throwing C# exceptions from C/C++. There are two types: 
 * Exceptions that take a message and ArgumentExceptions that take a message and a parameter name. */
typedef enum {
  SWIG_CSharpApplicationException,
  SWIG_CSharpArithmeticException,
  SWIG_CSharpDivideByZeroException,
  SWIG_CSharpIndexOutOfRangeException,
  SWIG_CSharpInvalidCastException,
  SWIG_CSharpInvalidOperationException,
  SWIG_CSharpIOException,
  SWIG_CSharpNullReferenceException,
  SWIG_CSharpOutOfMemoryException,
  SWIG_CSharpOverflowException,
  SWIG_CSharpSystemException
} SWIG_CSharpExceptionCodes;

typedef enum {
  SWIG_CSharpArgumentException,
  SWIG_CSharpArgumentNullException,
  SWIG_CSharpArgumentOutOfRangeException
} SWIG_CSharpExceptionArgumentCodes;

typedef void (SWIGSTDCALL* SWIG_CSharpExceptionCallback_t)(const char *);
typedef void (SWIGSTDCALL* SWIG_CSharpExceptionArgumentCallback_t)(const char *, const char *);

typedef struct {
  SWIG_CSharpExceptionCodes code;
  SWIG_CSharpExceptionCallback_t callback;
} SWIG_CSharpException_t;

typedef struct {
  SWIG_CSharpExceptionArgumentCodes code;
  SWIG_CSharpExceptionArgumentCallback_t callback;
} SWIG_CSharpExceptionArgument_t;

static SWIG_CSharpException_t SWIG_csharp_exceptions[] = {
  { SWIG_CSharpApplicationException, NULL },
  { SWIG_CSharpArithmeticException, NULL },
  { SWIG_CSharpDivideByZeroException, NULL },
  { SWIG_CSharpIndexOutOfRangeException, NULL },
  { SWIG_CSharpInvalidCastException, NULL },
  { SWIG_CSharpInvalidOperationException, NULL },
  { SWIG_CSharpIOException, NULL },
  { SWIG_CSharpNullReferenceException, NULL },
  { SWIG_CSharpOutOfMemoryException, NULL },
  { SWIG_CSharpOverflowException, NULL },
  { SWIG_CSharpSystemException, NULL }
};

static SWIG_CSharpExceptionArgument_t SWIG_csharp_exceptions_argument[] = {
  { SWIG_CSharpArgumentException, NULL },
  { SWIG_CSharpArgumentNullException, NULL },
  { SWIG_CSharpArgumentOutOfRangeException, NULL }
};

static void SWIGUNUSED SWIG_CSharpSetPendingException(SWIG_CSharpExceptionCodes code, const char *msg) {
  SWIG_CSharpExceptionCallback_t callback = SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback;
  if ((size_t)code < sizeof(SWIG_csharp_exceptions)/sizeof(SWIG_CSharpException_t)) {
    callback = SWIG_csharp_exceptions[code].callback;
  }
  callback(msg);
}

static void SWIGUNUSED SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpExceptionArgumentCodes code, const char *msg, const char *param_name) {
  SWIG_CSharpExceptionArgumentCallback_t callback = SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback;
  if ((size_t)code < sizeof(SWIG_csharp_exceptions_argument)/sizeof(SWIG_CSharpExceptionArgument_t)) {
    callback = SWIG_csharp_exceptions_argument[code].callback;
  }
  callback(msg, param_name);
}


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionCallbacks_MediasoupClient(
                                                SWIG_CSharpExceptionCallback_t applicationCallback,
                                                SWIG_CSharpExceptionCallback_t arithmeticCallback,
                                                SWIG_CSharpExceptionCallback_t divideByZeroCallback, 
                                                SWIG_CSharpExceptionCallback_t indexOutOfRangeCallback, 
                                                SWIG_CSharpExceptionCallback_t invalidCastCallback,
                                                SWIG_CSharpExceptionCallback_t invalidOperationCallback,
                                                SWIG_CSharpExceptionCallback_t ioCallback,
                                                SWIG_CSharpExceptionCallback_t nullReferenceCallback,
                                                SWIG_CSharpExceptionCallback_t outOfMemoryCallback, 
                                                SWIG_CSharpExceptionCallback_t overflowCallback, 
                                                SWIG_CSharpExceptionCallback_t systemCallback) {
  SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback = applicationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpArithmeticException].callback = arithmeticCallback;
  SWIG_csharp_exceptions[SWIG_CSharpDivideByZeroException].callback = divideByZeroCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIndexOutOfRangeException].callback = indexOutOfRangeCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidCastException].callback = invalidCastCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidOperationException].callback = invalidOperationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIOException].callback = ioCallback;
  SWIG_csharp_exceptions[SWIG_CSharpNullReferenceException].callback = nullReferenceCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOutOfMemoryException].callback = outOfMemoryCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOverflowException].callback = overflowCallback;
  SWIG_csharp_exceptions[SWIG_CSharpSystemException].callback = systemCallback;
}

#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionArgumentCallbacks_MediasoupClient(
                                                SWIG_CSharpExceptionArgumentCallback_t argumentCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentNullCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentOutOfRangeCallback) {
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback = argumentCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentNullException].callback = argumentNullCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentOutOfRangeException].callback = argumentOutOfRangeCallback;
}


/* Callback for returning strings to C# without leaking memory */
typedef char * (SWIGSTDCALL* SWIG_CSharpStringHelperCallback)(const char *);
static SWIG_CSharpStringHelperCallback SWIG_csharp_string_callback = NULL;


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterStringCallback_MediasoupClient(SWIG_CSharpStringHelperCallback callback) {
  SWIG_csharp_string_callback = callback;
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) do { if (!(expr)) {SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, msg, ""); return nullreturn; } } while (0)

/* -----------------------------------------------------------------------------
 * director_common.swg
 *
 * This file contains support for director classes which is common between
 * languages.
 * ----------------------------------------------------------------------------- */

/*
  Use -DSWIG_DIRECTOR_STATIC if you prefer to avoid the use of the
  'Swig' namespace. This could be useful for multi-modules projects.
*/
#ifdef SWIG_DIRECTOR_STATIC
/* Force anonymous (static) namespace */
#define Swig
#endif
/* -----------------------------------------------------------------------------
 * director.swg
 *
 * This file contains support for director classes so that C# proxy
 * methods can be called from C++.
 * ----------------------------------------------------------------------------- */

#if defined(DEBUG_DIRECTOR_OWNED)
#include <iostream>
#endif
#include <string>
#include <exception>

namespace Swig {
  /* Director base class - not currently used in C# directors */
  class Director {
  };

  /* Base class for director exceptions */
  class DirectorException : public std::exception {
  protected:
    std::string swig_msg;

  public:
    DirectorException(const char *msg) : swig_msg(msg) {
    }

    DirectorException(const std::string &msg) : swig_msg(msg) {
    }

    virtual ~DirectorException() throw() {
    }

    const char *what() const throw() {
      return swig_msg.c_str();
    }
  };

  /* Pure virtual method exception */
  class DirectorPureVirtualException : public DirectorException {
  public:
    DirectorPureVirtualException(const char *msg) : DirectorException(std::string("Attempt to invoke pure virtual method ") + msg) {
    }

    static void raise(const char *msg) {
      throw DirectorPureVirtualException(msg);
    }
  };
}


#ifdef __cplusplus
#include <utility>
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigSmartPointer {
    T *ptr;
    SwigSmartPointer(T *p) : ptr(p) { }
    ~SwigSmartPointer() { delete ptr; }
    SwigSmartPointer& operator=(SwigSmartPointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
    void reset(T *p) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = p; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigSmartPointer tmp(new T(t)); pointer = tmp; return *this; }
#if __cplusplus >=201103L
  SwigValueWrapper& operator=(T&& t) { SwigSmartPointer tmp(new T(std::move(t))); pointer = tmp; return *this; }
  operator T&&() const { return std::move(*pointer.ptr); }
#else
  operator T&() const { return *pointer.ptr; }
#endif
  T *operator&() const { return pointer.ptr; }
  static void reset(SwigValueWrapper& t, T *p) { t.pointer.reset(p); }
};

/*
 * SwigValueInit() is a generic initialisation solution as the following approach:
 * 
 *       T c_result = T();
 * 
 * doesn't compile for all types for example:
 * 
 *       unsigned int c_result = unsigned int();
 */
template <typename T> T SwigValueInit() {
  return T();
}

#if __cplusplus >=201103L
# define SWIG_STD_MOVE(OBJ) std::move(OBJ)
#else
# define SWIG_STD_MOVE(OBJ) OBJ
#endif

#endif


#include <string>


#include <json.hpp>


#include "absl/types/optional.h"
using namespace absl;


#include "DataProducer.hpp"



/* ---------------------------------------------------
 * C++ director class methods
 * --------------------------------------------------- */

#include "DataProducer_wrap.h"

SwigDirector_DataProducer_DataProducerListener::SwigDirector_DataProducer_DataProducerListener() : mediasoupclient::DataProducer::Listener(), Swig::Director() {
  swig_init_callbacks();
}

void SwigDirector_DataProducer_DataProducerListener::OnOpen(mediasoupclient::DataProducer *dataProducer) {
  void * jdataProducer = 0 ;
  
  if (!swig_callbackOnOpen) {
    Swig::DirectorPureVirtualException::raise("mediasoupclient::DataProducer::Listener::OnOpen");
    return;
  } else {
    jdataProducer = (void *) dataProducer; 
    swig_callbackOnOpen(jdataProducer);
  }
}

void SwigDirector_DataProducer_DataProducerListener::OnClose(mediasoupclient::DataProducer *dataProducer) {
  void * jdataProducer = 0 ;
  
  if (!swig_callbackOnClose) {
    Swig::DirectorPureVirtualException::raise("mediasoupclient::DataProducer::Listener::OnClose");
    return;
  } else {
    jdataProducer = (void *) dataProducer; 
    swig_callbackOnClose(jdataProducer);
  }
}

void SwigDirector_DataProducer_DataProducerListener::OnBufferedAmountChange(mediasoupclient::DataProducer *dataProducer,uint64_t sentDataSize) {
  void * jdataProducer = 0 ;
  void * jsentDataSize  ;
  
  if (!swig_callbackOnBufferedAmountChange) {
    Swig::DirectorPureVirtualException::raise("mediasoupclient::DataProducer::Listener::OnBufferedAmountChange");
    return;
  } else {
    jdataProducer = (void *) dataProducer; 
    jsentDataSize = (void *)new uint64_t(SWIG_STD_MOVE(sentDataSize)); 
    swig_callbackOnBufferedAmountChange(jdataProducer, jsentDataSize);
  }
}

void SwigDirector_DataProducer_DataProducerListener::OnTransportClose(mediasoupclient::DataProducer *dataProducer) {
  void * jdataProducer = 0 ;
  
  if (!swig_callbackOnTransportClose) {
    Swig::DirectorPureVirtualException::raise("mediasoupclient::DataProducer::Listener::OnTransportClose");
    return;
  } else {
    jdataProducer = (void *) dataProducer; 
    swig_callbackOnTransportClose(jdataProducer);
  }
}

void SwigDirector_DataProducer_DataProducerListener::swig_connect_director(SWIG_Callback0_t callbackOnOpen, SWIG_Callback1_t callbackOnClose, SWIG_Callback2_t callbackOnBufferedAmountChange, SWIG_Callback3_t callbackOnTransportClose) {
  swig_callbackOnOpen = callbackOnOpen;
  swig_callbackOnClose = callbackOnClose;
  swig_callbackOnBufferedAmountChange = callbackOnBufferedAmountChange;
  swig_callbackOnTransportClose = callbackOnTransportClose;
}

void SwigDirector_DataProducer_DataProducerListener::swig_init_callbacks() {
  swig_callbackOnOpen = 0;
  swig_callbackOnClose = 0;
  swig_callbackOnBufferedAmountChange = 0;
  swig_callbackOnTransportClose = 0;
}


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT void SWIGSTDCALL CSharp_AntelcatfMediasoupClient_RefCountInterface_AddRef___(void * jarg1) {
  rtc::RefCountInterface *arg1 = (rtc::RefCountInterface *) 0 ;
  
  arg1 = (rtc::RefCountInterface *)jarg1; 
  ((rtc::RefCountInterface const *)arg1)->AddRef();
}


SWIGEXPORT int SWIGSTDCALL CSharp_AntelcatfMediasoupClient_RefCountInterface_Release___(void * jarg1) {
  int jresult ;
  rtc::RefCountInterface *arg1 = (rtc::RefCountInterface *) 0 ;
  rtc::RefCountReleaseStatus result;
  
  arg1 = (rtc::RefCountInterface *)jarg1; 
  result = (rtc::RefCountReleaseStatus)((rtc::RefCountInterface const *)arg1)->Release();
  jresult = (int)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_AntelcatfMediasoupClient_DataChannelInit_reliable_set___(void * jarg1, unsigned int jarg2) {
  webrtc::DataChannelInit *arg1 = (webrtc::DataChannelInit *) 0 ;
  bool arg2 ;
  
  arg1 = (webrtc::DataChannelInit *)jarg1; 
  arg2 = jarg2 ? true : false; 
  if (arg1) (arg1)->reliable = arg2;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_AntelcatfMediasoupClient_DataChannelInit_reliable_get___(void * jarg1) {
  unsigned int jresult ;
  webrtc::DataChannelInit *arg1 = (webrtc::DataChannelInit *) 0 ;
  bool result;
  
  arg1 = (webrtc::DataChannelInit *)jarg1; 
  result = (bool) ((arg1)->reliable);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_AntelcatfMediasoupClient_DataChannelInit_ordered_set___(void * jarg1, unsigned int jarg2) {
  webrtc::DataChannelInit *arg1 = (webrtc::DataChannelInit *) 0 ;
  bool arg2 ;
  
  arg1 = (webrtc::DataChannelInit *)jarg1; 
  arg2 = jarg2 ? true : false; 
  if (arg1) (arg1)->ordered = arg2;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_AntelcatfMediasoupClient_DataChannelInit_ordered_get___(void * jarg1) {
  unsigned int jresult ;
  webrtc::DataChannelInit *arg1 = (webrtc::DataChannelInit *) 0 ;
  bool result;
  
  arg1 = (webrtc::DataChannelInit *)jarg1; 
  result = (bool) ((arg1)->ordered);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_AntelcatfMediasoupClient_DataChannelInit_maxRetransmitTime_set___(void * jarg1, void * jarg2) {
  webrtc::DataChannelInit *arg1 = (webrtc::DataChannelInit *) 0 ;
  absl::optional< int > arg2 ;
  
  arg1 = (webrtc::DataChannelInit *)jarg1; 
  {
    if (!$csinput.HasValue)
    arg2 = absl::optional::nullopt;
    else
    arg2 = absl::optional($csinput.Value);
  }
  if (arg1) (arg1)->maxRetransmitTime = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_AntelcatfMediasoupClient_DataChannelInit_maxRetransmitTime_get___(void * jarg1) {
  void * jresult ;
  webrtc::DataChannelInit *arg1 = (webrtc::DataChannelInit *) 0 ;
  absl::optional< int > result;
  
  arg1 = (webrtc::DataChannelInit *)jarg1; 
  result =  ((arg1)->maxRetransmitTime);
  jresult = new absl::optional< int >(result); 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_AntelcatfMediasoupClient_DataChannelInit_maxRetransmits_set___(void * jarg1, void * jarg2) {
  webrtc::DataChannelInit *arg1 = (webrtc::DataChannelInit *) 0 ;
  absl::optional< int > arg2 ;
  
  arg1 = (webrtc::DataChannelInit *)jarg1; 
  {
    if (!$csinput.HasValue)
    arg2 = absl::optional::nullopt;
    else
    arg2 = absl::optional($csinput.Value);
  }
  if (arg1) (arg1)->maxRetransmits = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_AntelcatfMediasoupClient_DataChannelInit_maxRetransmits_get___(void * jarg1) {
  void * jresult ;
  webrtc::DataChannelInit *arg1 = (webrtc::DataChannelInit *) 0 ;
  absl::optional< int > result;
  
  arg1 = (webrtc::DataChannelInit *)jarg1; 
  result =  ((arg1)->maxRetransmits);
  jresult = new absl::optional< int >(result); 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_AntelcatfMediasoupClient_DataChannelInit_protocol_set___(void * jarg1, const char * jarg2) {
  webrtc::DataChannelInit *arg1 = (webrtc::DataChannelInit *) 0 ;
  std::string *arg2 = 0 ;
  
  arg1 = (webrtc::DataChannelInit *)jarg1; 
  if (!jarg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return ;
  }
  std::string arg2_str(jarg2);
  arg2 = &arg2_str; 
  if (arg1) (arg1)->protocol = *arg2;
}


SWIGEXPORT const char * SWIGSTDCALL CSharp_AntelcatfMediasoupClient_DataChannelInit_protocol_get___(void * jarg1) {
  const char * jresult ;
  webrtc::DataChannelInit *arg1 = (webrtc::DataChannelInit *) 0 ;
  std::string *result = 0 ;
  
  arg1 = (webrtc::DataChannelInit *)jarg1; 
  result = (std::string *) & ((arg1)->protocol);
  jresult = SWIG_csharp_string_callback(result->c_str()); 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_AntelcatfMediasoupClient_DataChannelInit_negotiated_set___(void * jarg1, unsigned int jarg2) {
  webrtc::DataChannelInit *arg1 = (webrtc::DataChannelInit *) 0 ;
  bool arg2 ;
  
  arg1 = (webrtc::DataChannelInit *)jarg1; 
  arg2 = jarg2 ? true : false; 
  if (arg1) (arg1)->negotiated = arg2;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_AntelcatfMediasoupClient_DataChannelInit_negotiated_get___(void * jarg1) {
  unsigned int jresult ;
  webrtc::DataChannelInit *arg1 = (webrtc::DataChannelInit *) 0 ;
  bool result;
  
  arg1 = (webrtc::DataChannelInit *)jarg1; 
  result = (bool) ((arg1)->negotiated);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_AntelcatfMediasoupClient_DataChannelInit_id_set___(void * jarg1, int jarg2) {
  webrtc::DataChannelInit *arg1 = (webrtc::DataChannelInit *) 0 ;
  int arg2 ;
  
  arg1 = (webrtc::DataChannelInit *)jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->id = arg2;
}


SWIGEXPORT int SWIGSTDCALL CSharp_AntelcatfMediasoupClient_DataChannelInit_id_get___(void * jarg1) {
  int jresult ;
  webrtc::DataChannelInit *arg1 = (webrtc::DataChannelInit *) 0 ;
  int result;
  
  arg1 = (webrtc::DataChannelInit *)jarg1; 
  result = (int) ((arg1)->id);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_AntelcatfMediasoupClient_DataChannelInit_priority_set___(void * jarg1, void * jarg2) {
  webrtc::DataChannelInit *arg1 = (webrtc::DataChannelInit *) 0 ;
  absl::optional< Priority > arg2 ;
  absl::optional< Priority > *argp2 ;
  
  arg1 = (webrtc::DataChannelInit *)jarg1; 
  argp2 = (absl::optional< Priority > *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null absl::optional< Priority >", 0);
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->priority = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_AntelcatfMediasoupClient_DataChannelInit_priority_get___(void * jarg1) {
  void * jresult ;
  webrtc::DataChannelInit *arg1 = (webrtc::DataChannelInit *) 0 ;
  absl::optional< Priority > result;
  
  arg1 = (webrtc::DataChannelInit *)jarg1; 
  result =  ((arg1)->priority);
  jresult = new absl::optional< Priority >(result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_AntelcatfMediasoupClient_new_DataChannelInit___() {
  void * jresult ;
  webrtc::DataChannelInit *result = 0 ;
  
  result = (webrtc::DataChannelInit *)new webrtc::DataChannelInit();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_AntelcatfMediasoupClient_delete_DataChannelInit___(void * jarg1) {
  webrtc::DataChannelInit *arg1 = (webrtc::DataChannelInit *) 0 ;
  
  arg1 = (webrtc::DataChannelInit *)jarg1; 
  delete arg1;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_AntelcatfMediasoupClient_new_DataBuffer__SWIG_0___(void * jarg1, unsigned int jarg2) {
  void * jresult ;
  rtc::CopyOnWriteBuffer *arg1 = 0 ;
  bool arg2 ;
  webrtc::DataBuffer *result = 0 ;
  
  arg1 = (rtc::CopyOnWriteBuffer *)jarg1;
  if (!arg1) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "rtc::CopyOnWriteBuffer const & is null", 0);
    return 0;
  } 
  arg2 = jarg2 ? true : false; 
  result = (webrtc::DataBuffer *)new webrtc::DataBuffer((rtc::CopyOnWriteBuffer const &)*arg1,arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_AntelcatfMediasoupClient_new_DataBuffer__SWIG_1___(const char * jarg1) {
  void * jresult ;
  std::string *arg1 = 0 ;
  webrtc::DataBuffer *result = 0 ;
  
  if (!jarg1) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  std::string arg1_str(jarg1);
  arg1 = &arg1_str; 
  result = (webrtc::DataBuffer *)new webrtc::DataBuffer((std::string const &)*arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_AntelcatfMediasoupClient_DataBuffer_size___(void * jarg1) {
  unsigned long jresult ;
  webrtc::DataBuffer *arg1 = (webrtc::DataBuffer *) 0 ;
  size_t result;
  
  arg1 = (webrtc::DataBuffer *)jarg1; 
  result = ((webrtc::DataBuffer const *)arg1)->size();
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_AntelcatfMediasoupClient_DataBuffer_data_set___(void * jarg1, void * jarg2) {
  webrtc::DataBuffer *arg1 = (webrtc::DataBuffer *) 0 ;
  rtc::CopyOnWriteBuffer arg2 ;
  rtc::CopyOnWriteBuffer *argp2 ;
  
  arg1 = (webrtc::DataBuffer *)jarg1; 
  argp2 = (rtc::CopyOnWriteBuffer *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null rtc::CopyOnWriteBuffer", 0);
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->data = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_AntelcatfMediasoupClient_DataBuffer_data_get___(void * jarg1) {
  void * jresult ;
  webrtc::DataBuffer *arg1 = (webrtc::DataBuffer *) 0 ;
  rtc::CopyOnWriteBuffer result;
  
  arg1 = (webrtc::DataBuffer *)jarg1; 
  result =  ((arg1)->data);
  jresult = new rtc::CopyOnWriteBuffer(result); 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_AntelcatfMediasoupClient_DataBuffer_binary_set___(void * jarg1, unsigned int jarg2) {
  webrtc::DataBuffer *arg1 = (webrtc::DataBuffer *) 0 ;
  bool arg2 ;
  
  arg1 = (webrtc::DataBuffer *)jarg1; 
  arg2 = jarg2 ? true : false; 
  if (arg1) (arg1)->binary = arg2;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_AntelcatfMediasoupClient_DataBuffer_binary_get___(void * jarg1) {
  unsigned int jresult ;
  webrtc::DataBuffer *arg1 = (webrtc::DataBuffer *) 0 ;
  bool result;
  
  arg1 = (webrtc::DataBuffer *)jarg1; 
  result = (bool) ((arg1)->binary);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_AntelcatfMediasoupClient_delete_DataBuffer___(void * jarg1) {
  webrtc::DataBuffer *arg1 = (webrtc::DataBuffer *) 0 ;
  
  arg1 = (webrtc::DataBuffer *)jarg1; 
  delete arg1;
}


SWIGEXPORT void SWIGSTDCALL CSharp_AntelcatfMediasoupClient_DataChannelObserver_OnStateChange___(void * jarg1) {
  webrtc::DataChannelObserver *arg1 = (webrtc::DataChannelObserver *) 0 ;
  
  arg1 = (webrtc::DataChannelObserver *)jarg1; 
  (arg1)->OnStateChange();
}


SWIGEXPORT void SWIGSTDCALL CSharp_AntelcatfMediasoupClient_DataChannelObserver_OnMessage___(void * jarg1, void * jarg2) {
  webrtc::DataChannelObserver *arg1 = (webrtc::DataChannelObserver *) 0 ;
  webrtc::DataBuffer *arg2 = 0 ;
  
  arg1 = (webrtc::DataChannelObserver *)jarg1; 
  arg2 = (webrtc::DataBuffer *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "webrtc::DataBuffer const & is null", 0);
    return ;
  } 
  (arg1)->OnMessage((webrtc::DataBuffer const &)*arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_AntelcatfMediasoupClient_DataChannelObserver_OnBufferedAmountChange___(void * jarg1, void * jarg2) {
  webrtc::DataChannelObserver *arg1 = (webrtc::DataChannelObserver *) 0 ;
  uint64_t arg2 ;
  uint64_t *argp2 ;
  
  arg1 = (webrtc::DataChannelObserver *)jarg1; 
  argp2 = (uint64_t *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null uint64_t", 0);
    return ;
  }
  arg2 = *argp2; 
  (arg1)->OnBufferedAmountChange(arg2);
}


SWIGEXPORT char * SWIGSTDCALL CSharp_AntelcatfMediasoupClient_DataChannelInterface_DataStateString___(int jarg1) {
  char * jresult ;
  webrtc::DataChannelInterface::DataState arg1 ;
  char *result = 0 ;
  
  arg1 = (webrtc::DataChannelInterface::DataState)jarg1; 
  result = (char *)webrtc::DataChannelInterface::DataStateString(arg1);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_AntelcatfMediasoupClient_DataChannelInterface_RegisterObserver___(void * jarg1, void * jarg2) {
  webrtc::DataChannelInterface *arg1 = (webrtc::DataChannelInterface *) 0 ;
  webrtc::DataChannelObserver *arg2 = (webrtc::DataChannelObserver *) 0 ;
  
  arg1 = (webrtc::DataChannelInterface *)jarg1; 
  arg2 = (webrtc::DataChannelObserver *)jarg2; 
  (arg1)->RegisterObserver(arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_AntelcatfMediasoupClient_DataChannelInterface_UnregisterObserver___(void * jarg1) {
  webrtc::DataChannelInterface *arg1 = (webrtc::DataChannelInterface *) 0 ;
  
  arg1 = (webrtc::DataChannelInterface *)jarg1; 
  (arg1)->UnregisterObserver();
}


SWIGEXPORT const char * SWIGSTDCALL CSharp_AntelcatfMediasoupClient_DataChannelInterface_label___(void * jarg1) {
  const char * jresult ;
  webrtc::DataChannelInterface *arg1 = (webrtc::DataChannelInterface *) 0 ;
  std::string result;
  
  arg1 = (webrtc::DataChannelInterface *)jarg1; 
  result = ((webrtc::DataChannelInterface const *)arg1)->label();
  jresult = SWIG_csharp_string_callback((&result)->c_str()); 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_AntelcatfMediasoupClient_DataChannelInterface_reliable___(void * jarg1) {
  unsigned int jresult ;
  webrtc::DataChannelInterface *arg1 = (webrtc::DataChannelInterface *) 0 ;
  bool result;
  
  arg1 = (webrtc::DataChannelInterface *)jarg1; 
  result = (bool)((webrtc::DataChannelInterface const *)arg1)->reliable();
  jresult = result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_AntelcatfMediasoupClient_DataChannelInterface_ordered___(void * jarg1) {
  unsigned int jresult ;
  webrtc::DataChannelInterface *arg1 = (webrtc::DataChannelInterface *) 0 ;
  bool result;
  
  arg1 = (webrtc::DataChannelInterface *)jarg1; 
  result = (bool)((webrtc::DataChannelInterface const *)arg1)->ordered();
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_AntelcatfMediasoupClient_DataChannelInterface_maxRetransmitTime___(void * jarg1) {
  void * jresult ;
  webrtc::DataChannelInterface *arg1 = (webrtc::DataChannelInterface *) 0 ;
  uint16_t result;
  
  arg1 = (webrtc::DataChannelInterface *)jarg1; 
  result = ((webrtc::DataChannelInterface const *)arg1)->maxRetransmitTime();
  jresult = new uint16_t(result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_AntelcatfMediasoupClient_DataChannelInterface_maxRetransmits___(void * jarg1) {
  void * jresult ;
  webrtc::DataChannelInterface *arg1 = (webrtc::DataChannelInterface *) 0 ;
  uint16_t result;
  
  arg1 = (webrtc::DataChannelInterface *)jarg1; 
  result = ((webrtc::DataChannelInterface const *)arg1)->maxRetransmits();
  jresult = new uint16_t(result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_AntelcatfMediasoupClient_DataChannelInterface_maxRetransmitsOpt___(void * jarg1) {
  void * jresult ;
  webrtc::DataChannelInterface *arg1 = (webrtc::DataChannelInterface *) 0 ;
  absl::optional< int > result;
  
  arg1 = (webrtc::DataChannelInterface *)jarg1; 
  result = ((webrtc::DataChannelInterface const *)arg1)->maxRetransmitsOpt();
  jresult = new absl::optional< int >(result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_AntelcatfMediasoupClient_DataChannelInterface_maxPacketLifeTime___(void * jarg1) {
  void * jresult ;
  webrtc::DataChannelInterface *arg1 = (webrtc::DataChannelInterface *) 0 ;
  absl::optional< int > result;
  
  arg1 = (webrtc::DataChannelInterface *)jarg1; 
  result = ((webrtc::DataChannelInterface const *)arg1)->maxPacketLifeTime();
  jresult = new absl::optional< int >(result); 
  return jresult;
}


SWIGEXPORT const char * SWIGSTDCALL CSharp_AntelcatfMediasoupClient_DataChannelInterface_protocol___(void * jarg1) {
  const char * jresult ;
  webrtc::DataChannelInterface *arg1 = (webrtc::DataChannelInterface *) 0 ;
  std::string result;
  
  arg1 = (webrtc::DataChannelInterface *)jarg1; 
  result = ((webrtc::DataChannelInterface const *)arg1)->protocol();
  jresult = SWIG_csharp_string_callback((&result)->c_str()); 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_AntelcatfMediasoupClient_DataChannelInterface_negotiated___(void * jarg1) {
  unsigned int jresult ;
  webrtc::DataChannelInterface *arg1 = (webrtc::DataChannelInterface *) 0 ;
  bool result;
  
  arg1 = (webrtc::DataChannelInterface *)jarg1; 
  result = (bool)((webrtc::DataChannelInterface const *)arg1)->negotiated();
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_AntelcatfMediasoupClient_DataChannelInterface_id___(void * jarg1) {
  int jresult ;
  webrtc::DataChannelInterface *arg1 = (webrtc::DataChannelInterface *) 0 ;
  int result;
  
  arg1 = (webrtc::DataChannelInterface *)jarg1; 
  result = (int)((webrtc::DataChannelInterface const *)arg1)->id();
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_AntelcatfMediasoupClient_DataChannelInterface_priority___(void * jarg1) {
  void * jresult ;
  webrtc::DataChannelInterface *arg1 = (webrtc::DataChannelInterface *) 0 ;
  Priority result;
  
  arg1 = (webrtc::DataChannelInterface *)jarg1; 
  result = ((webrtc::DataChannelInterface const *)arg1)->priority();
  jresult = new Priority(result); 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_AntelcatfMediasoupClient_DataChannelInterface_state___(void * jarg1) {
  int jresult ;
  webrtc::DataChannelInterface *arg1 = (webrtc::DataChannelInterface *) 0 ;
  webrtc::DataChannelInterface::DataState result;
  
  arg1 = (webrtc::DataChannelInterface *)jarg1; 
  result = (webrtc::DataChannelInterface::DataState)((webrtc::DataChannelInterface const *)arg1)->state();
  jresult = (int)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_AntelcatfMediasoupClient_DataChannelInterface_error___(void * jarg1) {
  void * jresult ;
  webrtc::DataChannelInterface *arg1 = (webrtc::DataChannelInterface *) 0 ;
  RTCError result;
  
  arg1 = (webrtc::DataChannelInterface *)jarg1; 
  result = ((webrtc::DataChannelInterface const *)arg1)->error();
  jresult = new RTCError(result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_AntelcatfMediasoupClient_DataChannelInterface_messages_sent___(void * jarg1) {
  void * jresult ;
  webrtc::DataChannelInterface *arg1 = (webrtc::DataChannelInterface *) 0 ;
  uint32_t result;
  
  arg1 = (webrtc::DataChannelInterface *)jarg1; 
  result = ((webrtc::DataChannelInterface const *)arg1)->messages_sent();
  jresult = new uint32_t(result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_AntelcatfMediasoupClient_DataChannelInterface_bytes_sent___(void * jarg1) {
  void * jresult ;
  webrtc::DataChannelInterface *arg1 = (webrtc::DataChannelInterface *) 0 ;
  uint64_t result;
  
  arg1 = (webrtc::DataChannelInterface *)jarg1; 
  result = ((webrtc::DataChannelInterface const *)arg1)->bytes_sent();
  jresult = new uint64_t(result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_AntelcatfMediasoupClient_DataChannelInterface_messages_received___(void * jarg1) {
  void * jresult ;
  webrtc::DataChannelInterface *arg1 = (webrtc::DataChannelInterface *) 0 ;
  uint32_t result;
  
  arg1 = (webrtc::DataChannelInterface *)jarg1; 
  result = ((webrtc::DataChannelInterface const *)arg1)->messages_received();
  jresult = new uint32_t(result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_AntelcatfMediasoupClient_DataChannelInterface_bytes_received___(void * jarg1) {
  void * jresult ;
  webrtc::DataChannelInterface *arg1 = (webrtc::DataChannelInterface *) 0 ;
  uint64_t result;
  
  arg1 = (webrtc::DataChannelInterface *)jarg1; 
  result = ((webrtc::DataChannelInterface const *)arg1)->bytes_received();
  jresult = new uint64_t(result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_AntelcatfMediasoupClient_DataChannelInterface_buffered_amount___(void * jarg1) {
  void * jresult ;
  webrtc::DataChannelInterface *arg1 = (webrtc::DataChannelInterface *) 0 ;
  uint64_t result;
  
  arg1 = (webrtc::DataChannelInterface *)jarg1; 
  result = ((webrtc::DataChannelInterface const *)arg1)->buffered_amount();
  jresult = new uint64_t(result); 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_AntelcatfMediasoupClient_DataChannelInterface_Close___(void * jarg1) {
  webrtc::DataChannelInterface *arg1 = (webrtc::DataChannelInterface *) 0 ;
  
  arg1 = (webrtc::DataChannelInterface *)jarg1; 
  (arg1)->Close();
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_AntelcatfMediasoupClient_DataChannelInterface_Send___(void * jarg1, void * jarg2) {
  unsigned int jresult ;
  webrtc::DataChannelInterface *arg1 = (webrtc::DataChannelInterface *) 0 ;
  webrtc::DataBuffer *arg2 = 0 ;
  bool result;
  
  arg1 = (webrtc::DataChannelInterface *)jarg1; 
  arg2 = (webrtc::DataBuffer *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "webrtc::DataBuffer const & is null", 0);
    return 0;
  } 
  result = (bool)(arg1)->Send((webrtc::DataBuffer const &)*arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_AntelcatfMediasoupClient_DataProducer_PrivateListener_OnClose___(void * jarg1, void * jarg2) {
  mediasoupclient::DataProducer::PrivateListener *arg1 = (mediasoupclient::DataProducer::PrivateListener *) 0 ;
  mediasoupclient::DataProducer *arg2 = (mediasoupclient::DataProducer *) 0 ;
  
  arg1 = (mediasoupclient::DataProducer::PrivateListener *)jarg1; 
  arg2 = (mediasoupclient::DataProducer *)jarg2; 
  (arg1)->OnClose(arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_AntelcatfMediasoupClient_delete_DataProducer_PrivateListener___(void * jarg1) {
  mediasoupclient::DataProducer::PrivateListener *arg1 = (mediasoupclient::DataProducer::PrivateListener *) 0 ;
  
  arg1 = (mediasoupclient::DataProducer::PrivateListener *)jarg1; 
  delete arg1;
}


SWIGEXPORT void SWIGSTDCALL CSharp_AntelcatfMediasoupClient_DataProducer_DataProducerListener_OnOpen___(void * jarg1, void * jarg2) {
  mediasoupclient::DataProducer::Listener *arg1 = (mediasoupclient::DataProducer::Listener *) 0 ;
  mediasoupclient::DataProducer *arg2 = (mediasoupclient::DataProducer *) 0 ;
  
  arg1 = (mediasoupclient::DataProducer::Listener *)jarg1; 
  arg2 = (mediasoupclient::DataProducer *)jarg2; 
  (arg1)->OnOpen(arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_AntelcatfMediasoupClient_DataProducer_DataProducerListener_OnClose___(void * jarg1, void * jarg2) {
  mediasoupclient::DataProducer::Listener *arg1 = (mediasoupclient::DataProducer::Listener *) 0 ;
  mediasoupclient::DataProducer *arg2 = (mediasoupclient::DataProducer *) 0 ;
  
  arg1 = (mediasoupclient::DataProducer::Listener *)jarg1; 
  arg2 = (mediasoupclient::DataProducer *)jarg2; 
  (arg1)->OnClose(arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_AntelcatfMediasoupClient_DataProducer_DataProducerListener_OnBufferedAmountChange___(void * jarg1, void * jarg2, void * jarg3) {
  mediasoupclient::DataProducer::Listener *arg1 = (mediasoupclient::DataProducer::Listener *) 0 ;
  mediasoupclient::DataProducer *arg2 = (mediasoupclient::DataProducer *) 0 ;
  uint64_t arg3 ;
  uint64_t *argp3 ;
  
  arg1 = (mediasoupclient::DataProducer::Listener *)jarg1; 
  arg2 = (mediasoupclient::DataProducer *)jarg2; 
  argp3 = (uint64_t *)jarg3; 
  if (!argp3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null uint64_t", 0);
    return ;
  }
  arg3 = *argp3; 
  (arg1)->OnBufferedAmountChange(arg2,arg3);
}


SWIGEXPORT void SWIGSTDCALL CSharp_AntelcatfMediasoupClient_DataProducer_DataProducerListener_OnTransportClose___(void * jarg1, void * jarg2) {
  mediasoupclient::DataProducer::Listener *arg1 = (mediasoupclient::DataProducer::Listener *) 0 ;
  mediasoupclient::DataProducer *arg2 = (mediasoupclient::DataProducer *) 0 ;
  
  arg1 = (mediasoupclient::DataProducer::Listener *)jarg1; 
  arg2 = (mediasoupclient::DataProducer *)jarg2; 
  (arg1)->OnTransportClose(arg2);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_AntelcatfMediasoupClient_new_DataProducerListener___() {
  void * jresult ;
  mediasoupclient::DataProducer::Listener *result = 0 ;
  
  result = (mediasoupclient::DataProducer::Listener *)new SwigDirector_DataProducer_DataProducerListener();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_AntelcatfMediasoupClient_delete_DataProducer_DataProducerListener___(void * jarg1) {
  mediasoupclient::DataProducer::Listener *arg1 = (mediasoupclient::DataProducer::Listener *) 0 ;
  
  arg1 = (mediasoupclient::DataProducer::Listener *)jarg1; 
  delete arg1;
}


SWIGEXPORT void SWIGSTDCALL CSharp_AntelcatfMediasoupClient_DataProducer_DataProducerListener_director_connect___(void *objarg, SwigDirector_DataProducer_DataProducerListener::SWIG_Callback0_t callback0, SwigDirector_DataProducer_DataProducerListener::SWIG_Callback1_t callback1, SwigDirector_DataProducer_DataProducerListener::SWIG_Callback2_t callback2, SwigDirector_DataProducer_DataProducerListener::SWIG_Callback3_t callback3) {
  mediasoupclient::DataProducer::Listener *obj = (mediasoupclient::DataProducer::Listener *)objarg;
  SwigDirector_DataProducer_DataProducerListener *director = static_cast<SwigDirector_DataProducer_DataProducerListener *>(obj);
  director->swig_connect_director(callback0, callback1, callback2, callback3);
}


SWIGEXPORT const char * SWIGSTDCALL CSharp_AntelcatfMediasoupClient_DataProducer_GetId___(void * jarg1) {
  const char * jresult ;
  mediasoupclient::DataProducer *arg1 = (mediasoupclient::DataProducer *) 0 ;
  std::string *result = 0 ;
  
  arg1 = (mediasoupclient::DataProducer *)jarg1; 
  result = (std::string *) &((mediasoupclient::DataProducer const *)arg1)->GetId();
  jresult = SWIG_csharp_string_callback(result->c_str()); 
  return jresult;
}


SWIGEXPORT const char * SWIGSTDCALL CSharp_AntelcatfMediasoupClient_DataProducer_GetLocalId___(void * jarg1) {
  const char * jresult ;
  mediasoupclient::DataProducer *arg1 = (mediasoupclient::DataProducer *) 0 ;
  std::string result;
  
  arg1 = (mediasoupclient::DataProducer *)jarg1; 
  result = ((mediasoupclient::DataProducer const *)arg1)->GetLocalId();
  jresult = SWIG_csharp_string_callback((&result)->c_str()); 
  return jresult;
}


SWIGEXPORT string SWIGSTDCALL CSharp_AntelcatfMediasoupClient_DataProducer_GetSctpStreamParameters___(void * jarg1) {
  string jresult ;
  mediasoupclient::DataProducer *arg1 = (mediasoupclient::DataProducer *) 0 ;
  nlohmann::json *result = 0 ;
  
  arg1 = (mediasoupclient::DataProducer *)jarg1; 
  result = (nlohmann::json *) &((mediasoupclient::DataProducer const *)arg1)->GetSctpStreamParameters();
  jresult = SWIG_csharp_string_callback((&result)->dump()); 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_AntelcatfMediasoupClient_DataProducer_GetReadyState___(void * jarg1) {
  int jresult ;
  mediasoupclient::DataProducer *arg1 = (mediasoupclient::DataProducer *) 0 ;
  webrtc::DataChannelInterface::DataState result;
  
  arg1 = (mediasoupclient::DataProducer *)jarg1; 
  result = (webrtc::DataChannelInterface::DataState)((mediasoupclient::DataProducer const *)arg1)->GetReadyState();
  jresult = (int)result; 
  return jresult;
}


SWIGEXPORT const char * SWIGSTDCALL CSharp_AntelcatfMediasoupClient_DataProducer_GetLabel___(void * jarg1) {
  const char * jresult ;
  mediasoupclient::DataProducer *arg1 = (mediasoupclient::DataProducer *) 0 ;
  std::string result;
  
  arg1 = (mediasoupclient::DataProducer *)jarg1; 
  result = (arg1)->GetLabel();
  jresult = SWIG_csharp_string_callback((&result)->c_str()); 
  return jresult;
}


SWIGEXPORT const char * SWIGSTDCALL CSharp_AntelcatfMediasoupClient_DataProducer_GetProtocol___(void * jarg1) {
  const char * jresult ;
  mediasoupclient::DataProducer *arg1 = (mediasoupclient::DataProducer *) 0 ;
  std::string result;
  
  arg1 = (mediasoupclient::DataProducer *)jarg1; 
  result = (arg1)->GetProtocol();
  jresult = SWIG_csharp_string_callback((&result)->c_str()); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_AntelcatfMediasoupClient_DataProducer_GetBufferedAmount___(void * jarg1) {
  void * jresult ;
  mediasoupclient::DataProducer *arg1 = (mediasoupclient::DataProducer *) 0 ;
  uint64_t result;
  
  arg1 = (mediasoupclient::DataProducer *)jarg1; 
  result = ((mediasoupclient::DataProducer const *)arg1)->GetBufferedAmount();
  jresult = new uint64_t(result); 
  return jresult;
}


SWIGEXPORT string SWIGSTDCALL CSharp_AntelcatfMediasoupClient_DataProducer_GetAppData___(void * jarg1) {
  string jresult ;
  mediasoupclient::DataProducer *arg1 = (mediasoupclient::DataProducer *) 0 ;
  nlohmann::json *result = 0 ;
  
  arg1 = (mediasoupclient::DataProducer *)jarg1; 
  result = (nlohmann::json *) &((mediasoupclient::DataProducer const *)arg1)->GetAppData();
  jresult = SWIG_csharp_string_callback((&result)->dump()); 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_AntelcatfMediasoupClient_DataProducer_IsClosed___(void * jarg1) {
  unsigned int jresult ;
  mediasoupclient::DataProducer *arg1 = (mediasoupclient::DataProducer *) 0 ;
  bool result;
  
  arg1 = (mediasoupclient::DataProducer *)jarg1; 
  result = (bool)((mediasoupclient::DataProducer const *)arg1)->IsClosed();
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_AntelcatfMediasoupClient_DataProducer_Close___(void * jarg1) {
  mediasoupclient::DataProducer *arg1 = (mediasoupclient::DataProducer *) 0 ;
  
  arg1 = (mediasoupclient::DataProducer *)jarg1; 
  (arg1)->Close();
}


SWIGEXPORT void SWIGSTDCALL CSharp_AntelcatfMediasoupClient_DataProducer_Send___(void * jarg1, void * jarg2) {
  mediasoupclient::DataProducer *arg1 = (mediasoupclient::DataProducer *) 0 ;
  webrtc::DataBuffer *arg2 = 0 ;
  
  arg1 = (mediasoupclient::DataProducer *)jarg1; 
  arg2 = (webrtc::DataBuffer *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "webrtc::DataBuffer const & is null", 0);
    return ;
  } 
  (arg1)->Send((webrtc::DataBuffer const &)*arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_AntelcatfMediasoupClient_DataProducer_OnStateChange___(void * jarg1) {
  mediasoupclient::DataProducer *arg1 = (mediasoupclient::DataProducer *) 0 ;
  
  arg1 = (mediasoupclient::DataProducer *)jarg1; 
  (arg1)->OnStateChange();
}


SWIGEXPORT void SWIGSTDCALL CSharp_AntelcatfMediasoupClient_DataProducer_OnMessage___(void * jarg1, void * jarg2) {
  mediasoupclient::DataProducer *arg1 = (mediasoupclient::DataProducer *) 0 ;
  webrtc::DataBuffer *arg2 = 0 ;
  
  arg1 = (mediasoupclient::DataProducer *)jarg1; 
  arg2 = (webrtc::DataBuffer *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "webrtc::DataBuffer const & is null", 0);
    return ;
  } 
  (arg1)->OnMessage((webrtc::DataBuffer const &)*arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_AntelcatfMediasoupClient_DataProducer_OnBufferedAmountChange___(void * jarg1, void * jarg2) {
  mediasoupclient::DataProducer *arg1 = (mediasoupclient::DataProducer *) 0 ;
  uint64_t arg2 ;
  uint64_t *argp2 ;
  
  arg1 = (mediasoupclient::DataProducer *)jarg1; 
  argp2 = (uint64_t *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null uint64_t", 0);
    return ;
  }
  arg2 = *argp2; 
  (arg1)->OnBufferedAmountChange(arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_AntelcatfMediasoupClient_delete_DataProducer___(void * jarg1) {
  mediasoupclient::DataProducer *arg1 = (mediasoupclient::DataProducer *) 0 ;
  
  arg1 = (mediasoupclient::DataProducer *)jarg1; 
  delete arg1;
}


SWIGEXPORT rtc::RefCountInterface * SWIGSTDCALL CSharp_AntelcatfMediasoupClient_DataChannelInterface_SWIGUpcast___(webrtc::DataChannelInterface *jarg1) {
    return (rtc::RefCountInterface *)jarg1;
}

SWIGEXPORT mediasoupclient::DataProducer::Listener * SWIGSTDCALL CSharp_AntelcatfMediasoupClient_DataProducer_DataProducerListener_IDataProducerListener_GetInterfaceCPtr___(mediasoupclient::DataProducer::Listener *jarg1) {
    return (mediasoupclient::DataProducer::Listener *)jarg1;
}

SWIGEXPORT webrtc::DataChannelObserver * SWIGSTDCALL CSharp_AntelcatfMediasoupClient_DataProducer_SWIGUpcast___(mediasoupclient::DataProducer *jarg1) {
    return (webrtc::DataChannelObserver *)jarg1;
}

#ifdef __cplusplus
}
#endif

