/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_MediasoupClient_WRAP_H_
#define SWIG_MediasoupClient_WRAP_H_

class SwigDirector_DataProducer_DataProducerListener : public mediasoupclient::DataProducer::Listener, public Swig::Director {

public:
    SwigDirector_DataProducer_DataProducerListener();
    virtual void OnOpen(mediasoupclient::DataProducer *dataProducer);
    virtual void OnClose(mediasoupclient::DataProducer *dataProducer);
    virtual void OnBufferedAmountChange(mediasoupclient::DataProducer *dataProducer,uint64_t sentDataSize);
    virtual void OnTransportClose(mediasoupclient::DataProducer *dataProducer);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback1_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback2_t)(void *, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback3_t)(void *);
    void swig_connect_director(SWIG_Callback0_t callbackOnOpen, SWIG_Callback1_t callbackOnClose, SWIG_Callback2_t callbackOnBufferedAmountChange, SWIG_Callback3_t callbackOnTransportClose);

private:
    SWIG_Callback0_t swig_callbackOnOpen;
    SWIG_Callback1_t swig_callbackOnClose;
    SWIG_Callback2_t swig_callbackOnBufferedAmountChange;
    SWIG_Callback3_t swig_callbackOnTransportClose;
    void swig_init_callbacks();
};


#endif
