/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


#define SWIG_VERSION 0x040101
#define SWIGCSHARP

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


#include <stdlib.h>
#include <string.h>
#include <stdio.h>


/* Support for throwing C# exceptions from C/C++. There are two types: 
 * Exceptions that take a message and ArgumentExceptions that take a message and a parameter name. */
typedef enum {
  SWIG_CSharpApplicationException,
  SWIG_CSharpArithmeticException,
  SWIG_CSharpDivideByZeroException,
  SWIG_CSharpIndexOutOfRangeException,
  SWIG_CSharpInvalidCastException,
  SWIG_CSharpInvalidOperationException,
  SWIG_CSharpIOException,
  SWIG_CSharpNullReferenceException,
  SWIG_CSharpOutOfMemoryException,
  SWIG_CSharpOverflowException,
  SWIG_CSharpSystemException
} SWIG_CSharpExceptionCodes;

typedef enum {
  SWIG_CSharpArgumentException,
  SWIG_CSharpArgumentNullException,
  SWIG_CSharpArgumentOutOfRangeException
} SWIG_CSharpExceptionArgumentCodes;

typedef void (SWIGSTDCALL* SWIG_CSharpExceptionCallback_t)(const char *);
typedef void (SWIGSTDCALL* SWIG_CSharpExceptionArgumentCallback_t)(const char *, const char *);

typedef struct {
  SWIG_CSharpExceptionCodes code;
  SWIG_CSharpExceptionCallback_t callback;
} SWIG_CSharpException_t;

typedef struct {
  SWIG_CSharpExceptionArgumentCodes code;
  SWIG_CSharpExceptionArgumentCallback_t callback;
} SWIG_CSharpExceptionArgument_t;

static SWIG_CSharpException_t SWIG_csharp_exceptions[] = {
  { SWIG_CSharpApplicationException, NULL },
  { SWIG_CSharpArithmeticException, NULL },
  { SWIG_CSharpDivideByZeroException, NULL },
  { SWIG_CSharpIndexOutOfRangeException, NULL },
  { SWIG_CSharpInvalidCastException, NULL },
  { SWIG_CSharpInvalidOperationException, NULL },
  { SWIG_CSharpIOException, NULL },
  { SWIG_CSharpNullReferenceException, NULL },
  { SWIG_CSharpOutOfMemoryException, NULL },
  { SWIG_CSharpOverflowException, NULL },
  { SWIG_CSharpSystemException, NULL }
};

static SWIG_CSharpExceptionArgument_t SWIG_csharp_exceptions_argument[] = {
  { SWIG_CSharpArgumentException, NULL },
  { SWIG_CSharpArgumentNullException, NULL },
  { SWIG_CSharpArgumentOutOfRangeException, NULL }
};

static void SWIGUNUSED SWIG_CSharpSetPendingException(SWIG_CSharpExceptionCodes code, const char *msg) {
  SWIG_CSharpExceptionCallback_t callback = SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback;
  if ((size_t)code < sizeof(SWIG_csharp_exceptions)/sizeof(SWIG_CSharpException_t)) {
    callback = SWIG_csharp_exceptions[code].callback;
  }
  callback(msg);
}

static void SWIGUNUSED SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpExceptionArgumentCodes code, const char *msg, const char *param_name) {
  SWIG_CSharpExceptionArgumentCallback_t callback = SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback;
  if ((size_t)code < sizeof(SWIG_csharp_exceptions_argument)/sizeof(SWIG_CSharpExceptionArgument_t)) {
    callback = SWIG_csharp_exceptions_argument[code].callback;
  }
  callback(msg, param_name);
}


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionCallbacks_MediasoupClient(
                                                SWIG_CSharpExceptionCallback_t applicationCallback,
                                                SWIG_CSharpExceptionCallback_t arithmeticCallback,
                                                SWIG_CSharpExceptionCallback_t divideByZeroCallback, 
                                                SWIG_CSharpExceptionCallback_t indexOutOfRangeCallback, 
                                                SWIG_CSharpExceptionCallback_t invalidCastCallback,
                                                SWIG_CSharpExceptionCallback_t invalidOperationCallback,
                                                SWIG_CSharpExceptionCallback_t ioCallback,
                                                SWIG_CSharpExceptionCallback_t nullReferenceCallback,
                                                SWIG_CSharpExceptionCallback_t outOfMemoryCallback, 
                                                SWIG_CSharpExceptionCallback_t overflowCallback, 
                                                SWIG_CSharpExceptionCallback_t systemCallback) {
  SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback = applicationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpArithmeticException].callback = arithmeticCallback;
  SWIG_csharp_exceptions[SWIG_CSharpDivideByZeroException].callback = divideByZeroCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIndexOutOfRangeException].callback = indexOutOfRangeCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidCastException].callback = invalidCastCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidOperationException].callback = invalidOperationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIOException].callback = ioCallback;
  SWIG_csharp_exceptions[SWIG_CSharpNullReferenceException].callback = nullReferenceCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOutOfMemoryException].callback = outOfMemoryCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOverflowException].callback = overflowCallback;
  SWIG_csharp_exceptions[SWIG_CSharpSystemException].callback = systemCallback;
}

#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionArgumentCallbacks_MediasoupClient(
                                                SWIG_CSharpExceptionArgumentCallback_t argumentCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentNullCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentOutOfRangeCallback) {
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback = argumentCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentNullException].callback = argumentNullCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentOutOfRangeException].callback = argumentOutOfRangeCallback;
}


/* Callback for returning strings to C# without leaking memory */
typedef char * (SWIGSTDCALL* SWIG_CSharpStringHelperCallback)(const char *);
static SWIG_CSharpStringHelperCallback SWIG_csharp_string_callback = NULL;


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterStringCallback_MediasoupClient(SWIG_CSharpStringHelperCallback callback) {
  SWIG_csharp_string_callback = callback;
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) do { if (!(expr)) {SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, msg, ""); return nullreturn; } } while (0)


#ifdef __cplusplus
#include <utility>
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigSmartPointer {
    T *ptr;
    SwigSmartPointer(T *p) : ptr(p) { }
    ~SwigSmartPointer() { delete ptr; }
    SwigSmartPointer& operator=(SwigSmartPointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
    void reset(T *p) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = p; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigSmartPointer tmp(new T(t)); pointer = tmp; return *this; }
#if __cplusplus >=201103L
  SwigValueWrapper& operator=(T&& t) { SwigSmartPointer tmp(new T(std::move(t))); pointer = tmp; return *this; }
  operator T&&() const { return std::move(*pointer.ptr); }
#else
  operator T&() const { return *pointer.ptr; }
#endif
  T *operator&() const { return pointer.ptr; }
  static void reset(SwigValueWrapper& t, T *p) { t.pointer.reset(p); }
};

/*
 * SwigValueInit() is a generic initialisation solution as the following approach:
 * 
 *       T c_result = T();
 * 
 * doesn't compile for all types for example:
 * 
 *       unsigned int c_result = unsigned int();
 */
template <typename T> T SwigValueInit() {
  return T();
}

#if __cplusplus >=201103L
# define SWIG_STD_MOVE(OBJ) std::move(OBJ)
#else
# define SWIG_STD_MOVE(OBJ) OBJ
#endif

#endif


#include <string>


#include <json.hpp>


#include "Device.h"


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT void * SWIGSTDCALL CSharp_AntelcatfMediasoupClient_new_Device___() {
  void * jresult ;
  mediasoupclient::Device *result = 0 ;
  
  result = (mediasoupclient::Device *)new mediasoupclient::Device();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_AntelcatfMediasoupClient_delete_Device___(void * jarg1) {
  mediasoupclient::Device *arg1 = (mediasoupclient::Device *) 0 ;
  
  arg1 = (mediasoupclient::Device *)jarg1; 
  delete arg1;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_AntelcatfMediasoupClient_Device_IsLoaded___(void * jarg1) {
  unsigned int jresult ;
  mediasoupclient::Device *arg1 = (mediasoupclient::Device *) 0 ;
  bool result;
  
  arg1 = (mediasoupclient::Device *)jarg1; 
  result = (bool)((mediasoupclient::Device const *)arg1)->IsLoaded();
  jresult = result; 
  return jresult;
}


SWIGEXPORT string SWIGSTDCALL CSharp_AntelcatfMediasoupClient_Device_GetRtpCapabilities___(void * jarg1) {
  string jresult ;
  mediasoupclient::Device *arg1 = (mediasoupclient::Device *) 0 ;
  nlohmann::json *result = 0 ;
  
  arg1 = (mediasoupclient::Device *)jarg1; 
  result = (nlohmann::json *) &((mediasoupclient::Device const *)arg1)->GetRtpCapabilities();
  jresult = SWIG_csharp_string_callback((&result)->dump()); 
  return jresult;
}


SWIGEXPORT string SWIGSTDCALL CSharp_AntelcatfMediasoupClient_Device_GetSctpCapabilities___(void * jarg1) {
  string jresult ;
  mediasoupclient::Device *arg1 = (mediasoupclient::Device *) 0 ;
  nlohmann::json *result = 0 ;
  
  arg1 = (mediasoupclient::Device *)jarg1; 
  result = (nlohmann::json *) &((mediasoupclient::Device const *)arg1)->GetSctpCapabilities();
  jresult = SWIG_csharp_string_callback((&result)->dump()); 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_AntelcatfMediasoupClient_Device_Load__SWIG_0___(void * jarg1, string jarg2, void * jarg3) {
  mediasoupclient::Device *arg1 = (mediasoupclient::Device *) 0 ;
  nlohmann::json arg2 ;
  PeerConnection::Options *arg3 = (PeerConnection::Options *) 0 ;
  
  arg1 = (mediasoupclient::Device *)jarg1; 
  if (!jarg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return ;
  }
  (&arg2)->parse(jarg2); 
  arg3 = (PeerConnection::Options *)jarg3; 
  (arg1)->Load(arg2,(PeerConnection::Options const *)arg3);
}


SWIGEXPORT void SWIGSTDCALL CSharp_AntelcatfMediasoupClient_Device_Load__SWIG_1___(void * jarg1, string jarg2) {
  mediasoupclient::Device *arg1 = (mediasoupclient::Device *) 0 ;
  nlohmann::json arg2 ;
  
  arg1 = (mediasoupclient::Device *)jarg1; 
  if (!jarg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return ;
  }
  (&arg2)->parse(jarg2); 
  (arg1)->Load(arg2);
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_AntelcatfMediasoupClient_Device_CanProduce___(void * jarg1, const char * jarg2) {
  unsigned int jresult ;
  mediasoupclient::Device *arg1 = (mediasoupclient::Device *) 0 ;
  std::string *arg2 = 0 ;
  bool result;
  
  arg1 = (mediasoupclient::Device *)jarg1; 
  if (!jarg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  std::string arg2_str(jarg2);
  arg2 = &arg2_str; 
  result = (bool)(arg1)->CanProduce((std::string const &)*arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_AntelcatfMediasoupClient_Device_CreateSendTransport__SWIG_0___(void * jarg1, void * jarg2, const char * jarg3, string jarg4, string jarg5, string jarg6, string jarg7, void * jarg8, string jarg9) {
  void * jresult ;
  mediasoupclient::Device *arg1 = (mediasoupclient::Device *) 0 ;
  SendTransport::Listener *arg2 = (SendTransport::Listener *) 0 ;
  std::string *arg3 = 0 ;
  nlohmann::json *arg4 = 0 ;
  nlohmann::json *arg5 = 0 ;
  nlohmann::json *arg6 = 0 ;
  nlohmann::json *arg7 = 0 ;
  PeerConnection::Options *arg8 = (PeerConnection::Options *) 0 ;
  nlohmann::json *arg9 = 0 ;
  SendTransport *result = 0 ;
  
  arg1 = (mediasoupclient::Device *)jarg1; 
  arg2 = (SendTransport::Listener *)jarg2; 
  if (!jarg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  std::string arg3_str(jarg3);
  arg3 = &arg3_str; 
  if (!jarg4) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  (&arg4)->parse(jarg4); 
  if (!jarg5) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  (&arg5)->parse(jarg5); 
  if (!jarg6) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  (&arg6)->parse(jarg6); 
  if (!jarg7) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  (&arg7)->parse(jarg7); 
  arg8 = (PeerConnection::Options *)jarg8; 
  if (!jarg9) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  (&arg9)->parse(jarg9); 
  result = (SendTransport *)((mediasoupclient::Device const *)arg1)->CreateSendTransport(arg2,(std::string const &)*arg3,(nlohmann::json const &)*arg4,(nlohmann::json const &)*arg5,(nlohmann::json const &)*arg6,(nlohmann::json const &)*arg7,(PeerConnection::Options const *)arg8,(nlohmann::json const &)*arg9);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_AntelcatfMediasoupClient_Device_CreateSendTransport__SWIG_1___(void * jarg1, void * jarg2, const char * jarg3, string jarg4, string jarg5, string jarg6, string jarg7, void * jarg8) {
  void * jresult ;
  mediasoupclient::Device *arg1 = (mediasoupclient::Device *) 0 ;
  SendTransport::Listener *arg2 = (SendTransport::Listener *) 0 ;
  std::string *arg3 = 0 ;
  nlohmann::json *arg4 = 0 ;
  nlohmann::json *arg5 = 0 ;
  nlohmann::json *arg6 = 0 ;
  nlohmann::json *arg7 = 0 ;
  PeerConnection::Options *arg8 = (PeerConnection::Options *) 0 ;
  SendTransport *result = 0 ;
  
  arg1 = (mediasoupclient::Device *)jarg1; 
  arg2 = (SendTransport::Listener *)jarg2; 
  if (!jarg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  std::string arg3_str(jarg3);
  arg3 = &arg3_str; 
  if (!jarg4) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  (&arg4)->parse(jarg4); 
  if (!jarg5) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  (&arg5)->parse(jarg5); 
  if (!jarg6) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  (&arg6)->parse(jarg6); 
  if (!jarg7) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  (&arg7)->parse(jarg7); 
  arg8 = (PeerConnection::Options *)jarg8; 
  result = (SendTransport *)((mediasoupclient::Device const *)arg1)->CreateSendTransport(arg2,(std::string const &)*arg3,(nlohmann::json const &)*arg4,(nlohmann::json const &)*arg5,(nlohmann::json const &)*arg6,(nlohmann::json const &)*arg7,(PeerConnection::Options const *)arg8);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_AntelcatfMediasoupClient_Device_CreateSendTransport__SWIG_2___(void * jarg1, void * jarg2, const char * jarg3, string jarg4, string jarg5, string jarg6, string jarg7) {
  void * jresult ;
  mediasoupclient::Device *arg1 = (mediasoupclient::Device *) 0 ;
  SendTransport::Listener *arg2 = (SendTransport::Listener *) 0 ;
  std::string *arg3 = 0 ;
  nlohmann::json *arg4 = 0 ;
  nlohmann::json *arg5 = 0 ;
  nlohmann::json *arg6 = 0 ;
  nlohmann::json *arg7 = 0 ;
  SendTransport *result = 0 ;
  
  arg1 = (mediasoupclient::Device *)jarg1; 
  arg2 = (SendTransport::Listener *)jarg2; 
  if (!jarg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  std::string arg3_str(jarg3);
  arg3 = &arg3_str; 
  if (!jarg4) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  (&arg4)->parse(jarg4); 
  if (!jarg5) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  (&arg5)->parse(jarg5); 
  if (!jarg6) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  (&arg6)->parse(jarg6); 
  if (!jarg7) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  (&arg7)->parse(jarg7); 
  result = (SendTransport *)((mediasoupclient::Device const *)arg1)->CreateSendTransport(arg2,(std::string const &)*arg3,(nlohmann::json const &)*arg4,(nlohmann::json const &)*arg5,(nlohmann::json const &)*arg6,(nlohmann::json const &)*arg7);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_AntelcatfMediasoupClient_Device_CreateSendTransport__SWIG_3___(void * jarg1, void * jarg2, const char * jarg3, string jarg4, string jarg5, string jarg6, void * jarg7, string jarg8) {
  void * jresult ;
  mediasoupclient::Device *arg1 = (mediasoupclient::Device *) 0 ;
  SendTransport::Listener *arg2 = (SendTransport::Listener *) 0 ;
  std::string *arg3 = 0 ;
  nlohmann::json *arg4 = 0 ;
  nlohmann::json *arg5 = 0 ;
  nlohmann::json *arg6 = 0 ;
  PeerConnection::Options *arg7 = (PeerConnection::Options *) 0 ;
  nlohmann::json *arg8 = 0 ;
  SendTransport *result = 0 ;
  
  arg1 = (mediasoupclient::Device *)jarg1; 
  arg2 = (SendTransport::Listener *)jarg2; 
  if (!jarg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  std::string arg3_str(jarg3);
  arg3 = &arg3_str; 
  if (!jarg4) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  (&arg4)->parse(jarg4); 
  if (!jarg5) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  (&arg5)->parse(jarg5); 
  if (!jarg6) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  (&arg6)->parse(jarg6); 
  arg7 = (PeerConnection::Options *)jarg7; 
  if (!jarg8) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  (&arg8)->parse(jarg8); 
  result = (SendTransport *)((mediasoupclient::Device const *)arg1)->CreateSendTransport(arg2,(std::string const &)*arg3,(nlohmann::json const &)*arg4,(nlohmann::json const &)*arg5,(nlohmann::json const &)*arg6,(PeerConnection::Options const *)arg7,(nlohmann::json const &)*arg8);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_AntelcatfMediasoupClient_Device_CreateSendTransport__SWIG_4___(void * jarg1, void * jarg2, const char * jarg3, string jarg4, string jarg5, string jarg6, void * jarg7) {
  void * jresult ;
  mediasoupclient::Device *arg1 = (mediasoupclient::Device *) 0 ;
  SendTransport::Listener *arg2 = (SendTransport::Listener *) 0 ;
  std::string *arg3 = 0 ;
  nlohmann::json *arg4 = 0 ;
  nlohmann::json *arg5 = 0 ;
  nlohmann::json *arg6 = 0 ;
  PeerConnection::Options *arg7 = (PeerConnection::Options *) 0 ;
  SendTransport *result = 0 ;
  
  arg1 = (mediasoupclient::Device *)jarg1; 
  arg2 = (SendTransport::Listener *)jarg2; 
  if (!jarg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  std::string arg3_str(jarg3);
  arg3 = &arg3_str; 
  if (!jarg4) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  (&arg4)->parse(jarg4); 
  if (!jarg5) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  (&arg5)->parse(jarg5); 
  if (!jarg6) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  (&arg6)->parse(jarg6); 
  arg7 = (PeerConnection::Options *)jarg7; 
  result = (SendTransport *)((mediasoupclient::Device const *)arg1)->CreateSendTransport(arg2,(std::string const &)*arg3,(nlohmann::json const &)*arg4,(nlohmann::json const &)*arg5,(nlohmann::json const &)*arg6,(PeerConnection::Options const *)arg7);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_AntelcatfMediasoupClient_Device_CreateSendTransport__SWIG_5___(void * jarg1, void * jarg2, const char * jarg3, string jarg4, string jarg5, string jarg6) {
  void * jresult ;
  mediasoupclient::Device *arg1 = (mediasoupclient::Device *) 0 ;
  SendTransport::Listener *arg2 = (SendTransport::Listener *) 0 ;
  std::string *arg3 = 0 ;
  nlohmann::json *arg4 = 0 ;
  nlohmann::json *arg5 = 0 ;
  nlohmann::json *arg6 = 0 ;
  SendTransport *result = 0 ;
  
  arg1 = (mediasoupclient::Device *)jarg1; 
  arg2 = (SendTransport::Listener *)jarg2; 
  if (!jarg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  std::string arg3_str(jarg3);
  arg3 = &arg3_str; 
  if (!jarg4) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  (&arg4)->parse(jarg4); 
  if (!jarg5) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  (&arg5)->parse(jarg5); 
  if (!jarg6) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  (&arg6)->parse(jarg6); 
  result = (SendTransport *)((mediasoupclient::Device const *)arg1)->CreateSendTransport(arg2,(std::string const &)*arg3,(nlohmann::json const &)*arg4,(nlohmann::json const &)*arg5,(nlohmann::json const &)*arg6);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_AntelcatfMediasoupClient_Device_CreateRecvTransport__SWIG_0___(void * jarg1, void * jarg2, const char * jarg3, string jarg4, string jarg5, string jarg6, string jarg7, void * jarg8, string jarg9) {
  void * jresult ;
  mediasoupclient::Device *arg1 = (mediasoupclient::Device *) 0 ;
  RecvTransport::Listener *arg2 = (RecvTransport::Listener *) 0 ;
  std::string *arg3 = 0 ;
  nlohmann::json *arg4 = 0 ;
  nlohmann::json *arg5 = 0 ;
  nlohmann::json *arg6 = 0 ;
  nlohmann::json *arg7 = 0 ;
  PeerConnection::Options *arg8 = (PeerConnection::Options *) 0 ;
  nlohmann::json *arg9 = 0 ;
  RecvTransport *result = 0 ;
  
  arg1 = (mediasoupclient::Device *)jarg1; 
  arg2 = (RecvTransport::Listener *)jarg2; 
  if (!jarg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  std::string arg3_str(jarg3);
  arg3 = &arg3_str; 
  if (!jarg4) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  (&arg4)->parse(jarg4); 
  if (!jarg5) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  (&arg5)->parse(jarg5); 
  if (!jarg6) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  (&arg6)->parse(jarg6); 
  if (!jarg7) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  (&arg7)->parse(jarg7); 
  arg8 = (PeerConnection::Options *)jarg8; 
  if (!jarg9) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  (&arg9)->parse(jarg9); 
  result = (RecvTransport *)((mediasoupclient::Device const *)arg1)->CreateRecvTransport(arg2,(std::string const &)*arg3,(nlohmann::json const &)*arg4,(nlohmann::json const &)*arg5,(nlohmann::json const &)*arg6,(nlohmann::json const &)*arg7,(PeerConnection::Options const *)arg8,(nlohmann::json const &)*arg9);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_AntelcatfMediasoupClient_Device_CreateRecvTransport__SWIG_1___(void * jarg1, void * jarg2, const char * jarg3, string jarg4, string jarg5, string jarg6, string jarg7, void * jarg8) {
  void * jresult ;
  mediasoupclient::Device *arg1 = (mediasoupclient::Device *) 0 ;
  RecvTransport::Listener *arg2 = (RecvTransport::Listener *) 0 ;
  std::string *arg3 = 0 ;
  nlohmann::json *arg4 = 0 ;
  nlohmann::json *arg5 = 0 ;
  nlohmann::json *arg6 = 0 ;
  nlohmann::json *arg7 = 0 ;
  PeerConnection::Options *arg8 = (PeerConnection::Options *) 0 ;
  RecvTransport *result = 0 ;
  
  arg1 = (mediasoupclient::Device *)jarg1; 
  arg2 = (RecvTransport::Listener *)jarg2; 
  if (!jarg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  std::string arg3_str(jarg3);
  arg3 = &arg3_str; 
  if (!jarg4) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  (&arg4)->parse(jarg4); 
  if (!jarg5) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  (&arg5)->parse(jarg5); 
  if (!jarg6) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  (&arg6)->parse(jarg6); 
  if (!jarg7) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  (&arg7)->parse(jarg7); 
  arg8 = (PeerConnection::Options *)jarg8; 
  result = (RecvTransport *)((mediasoupclient::Device const *)arg1)->CreateRecvTransport(arg2,(std::string const &)*arg3,(nlohmann::json const &)*arg4,(nlohmann::json const &)*arg5,(nlohmann::json const &)*arg6,(nlohmann::json const &)*arg7,(PeerConnection::Options const *)arg8);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_AntelcatfMediasoupClient_Device_CreateRecvTransport__SWIG_2___(void * jarg1, void * jarg2, const char * jarg3, string jarg4, string jarg5, string jarg6, string jarg7) {
  void * jresult ;
  mediasoupclient::Device *arg1 = (mediasoupclient::Device *) 0 ;
  RecvTransport::Listener *arg2 = (RecvTransport::Listener *) 0 ;
  std::string *arg3 = 0 ;
  nlohmann::json *arg4 = 0 ;
  nlohmann::json *arg5 = 0 ;
  nlohmann::json *arg6 = 0 ;
  nlohmann::json *arg7 = 0 ;
  RecvTransport *result = 0 ;
  
  arg1 = (mediasoupclient::Device *)jarg1; 
  arg2 = (RecvTransport::Listener *)jarg2; 
  if (!jarg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  std::string arg3_str(jarg3);
  arg3 = &arg3_str; 
  if (!jarg4) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  (&arg4)->parse(jarg4); 
  if (!jarg5) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  (&arg5)->parse(jarg5); 
  if (!jarg6) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  (&arg6)->parse(jarg6); 
  if (!jarg7) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  (&arg7)->parse(jarg7); 
  result = (RecvTransport *)((mediasoupclient::Device const *)arg1)->CreateRecvTransport(arg2,(std::string const &)*arg3,(nlohmann::json const &)*arg4,(nlohmann::json const &)*arg5,(nlohmann::json const &)*arg6,(nlohmann::json const &)*arg7);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_AntelcatfMediasoupClient_Device_CreateRecvTransport__SWIG_3___(void * jarg1, void * jarg2, const char * jarg3, string jarg4, string jarg5, string jarg6, void * jarg7, string jarg8) {
  void * jresult ;
  mediasoupclient::Device *arg1 = (mediasoupclient::Device *) 0 ;
  RecvTransport::Listener *arg2 = (RecvTransport::Listener *) 0 ;
  std::string *arg3 = 0 ;
  nlohmann::json *arg4 = 0 ;
  nlohmann::json *arg5 = 0 ;
  nlohmann::json *arg6 = 0 ;
  PeerConnection::Options *arg7 = (PeerConnection::Options *) 0 ;
  nlohmann::json *arg8 = 0 ;
  RecvTransport *result = 0 ;
  
  arg1 = (mediasoupclient::Device *)jarg1; 
  arg2 = (RecvTransport::Listener *)jarg2; 
  if (!jarg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  std::string arg3_str(jarg3);
  arg3 = &arg3_str; 
  if (!jarg4) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  (&arg4)->parse(jarg4); 
  if (!jarg5) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  (&arg5)->parse(jarg5); 
  if (!jarg6) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  (&arg6)->parse(jarg6); 
  arg7 = (PeerConnection::Options *)jarg7; 
  if (!jarg8) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  (&arg8)->parse(jarg8); 
  result = (RecvTransport *)((mediasoupclient::Device const *)arg1)->CreateRecvTransport(arg2,(std::string const &)*arg3,(nlohmann::json const &)*arg4,(nlohmann::json const &)*arg5,(nlohmann::json const &)*arg6,(PeerConnection::Options const *)arg7,(nlohmann::json const &)*arg8);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_AntelcatfMediasoupClient_Device_CreateRecvTransport__SWIG_4___(void * jarg1, void * jarg2, const char * jarg3, string jarg4, string jarg5, string jarg6, void * jarg7) {
  void * jresult ;
  mediasoupclient::Device *arg1 = (mediasoupclient::Device *) 0 ;
  RecvTransport::Listener *arg2 = (RecvTransport::Listener *) 0 ;
  std::string *arg3 = 0 ;
  nlohmann::json *arg4 = 0 ;
  nlohmann::json *arg5 = 0 ;
  nlohmann::json *arg6 = 0 ;
  PeerConnection::Options *arg7 = (PeerConnection::Options *) 0 ;
  RecvTransport *result = 0 ;
  
  arg1 = (mediasoupclient::Device *)jarg1; 
  arg2 = (RecvTransport::Listener *)jarg2; 
  if (!jarg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  std::string arg3_str(jarg3);
  arg3 = &arg3_str; 
  if (!jarg4) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  (&arg4)->parse(jarg4); 
  if (!jarg5) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  (&arg5)->parse(jarg5); 
  if (!jarg6) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  (&arg6)->parse(jarg6); 
  arg7 = (PeerConnection::Options *)jarg7; 
  result = (RecvTransport *)((mediasoupclient::Device const *)arg1)->CreateRecvTransport(arg2,(std::string const &)*arg3,(nlohmann::json const &)*arg4,(nlohmann::json const &)*arg5,(nlohmann::json const &)*arg6,(PeerConnection::Options const *)arg7);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_AntelcatfMediasoupClient_Device_CreateRecvTransport__SWIG_5___(void * jarg1, void * jarg2, const char * jarg3, string jarg4, string jarg5, string jarg6) {
  void * jresult ;
  mediasoupclient::Device *arg1 = (mediasoupclient::Device *) 0 ;
  RecvTransport::Listener *arg2 = (RecvTransport::Listener *) 0 ;
  std::string *arg3 = 0 ;
  nlohmann::json *arg4 = 0 ;
  nlohmann::json *arg5 = 0 ;
  nlohmann::json *arg6 = 0 ;
  RecvTransport *result = 0 ;
  
  arg1 = (mediasoupclient::Device *)jarg1; 
  arg2 = (RecvTransport::Listener *)jarg2; 
  if (!jarg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  std::string arg3_str(jarg3);
  arg3 = &arg3_str; 
  if (!jarg4) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  (&arg4)->parse(jarg4); 
  if (!jarg5) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  (&arg5)->parse(jarg5); 
  if (!jarg6) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  (&arg6)->parse(jarg6); 
  result = (RecvTransport *)((mediasoupclient::Device const *)arg1)->CreateRecvTransport(arg2,(std::string const &)*arg3,(nlohmann::json const &)*arg4,(nlohmann::json const &)*arg5,(nlohmann::json const &)*arg6);
  jresult = (void *)result; 
  return jresult;
}


#ifdef __cplusplus
}
#endif

