%include "json.i"
%include "basic.i"
%include "std_map.i"
%include "std_vector.i"
%include "std_string.i"
%include "std_future.i"
%include "std_unique_ptr.i"
%include "webrtc/data_channel_interface.i"
%include "webrtc/peer_connection_interface.i"

%include "PeerConnection.hpp"